<?php

namespace App\Services;

use App\Contracts\OmadaServiceInterface;
use App\Models\Student;
use App\Models\Visitor;
use App\Models\WifiAccessLog;
use App\Models\WifiVoucher;

class VoucherAssignmentService
{
    public function __construct(
        protected OmadaServiceInterface $omada
    ) {}

    public function issueForStudent(Student $student, int $durationMinutes = 480): bool|array
    {
        $existingVoucher = $this->getActiveVoucherForStudent($student);

        if ($existingVoucher) {
            return false;
        }

        return $this->assignVoucher(
            subject: $student,
            voucherType: 'student',
            durationMinutes: $durationMinutes,
            subjectKey: 'student_id',
        );
    }

    public function issueForVisitor(Visitor $visitor, int $durationMinutes = 480): bool|array
    {
        $existingVoucher = $this->getActiveVoucherForVisitor($visitor);

        if ($existingVoucher) {
            return false;
        }

        return $this->assignVoucher(
            subject: $visitor,
            voucherType: 'visitor',
            durationMinutes: $durationMinutes,
            subjectKey: 'visitor_id',
        );
    }

    public function getActiveVoucherForStudent(Student $student): ?WifiVoucher
    {
        return $student->wifiVouchers()
            ->where('status', 'active')
            ->where('expires_at', '>', now())
            ->latest()
            ->first();
    }

    public function getActiveVoucherForVisitor(Visitor $visitor): ?WifiVoucher
    {
        return $visitor->wifiVouchers()
            ->where('status', 'active')
            ->where('expires_at', '>', now())
            ->latest()
            ->first();
    }

    /**
     * @param  Student|Visitor  $subject
     * @return array<string, mixed>|bool
     */
    protected function assignVoucher($subject, string $voucherType, int $durationMinutes, string $subjectKey): bool|array
    {
        $voucherData = $this->omada->createVoucher($durationMinutes);

        $voucher = WifiVoucher::create([
            $subjectKey => $subject->id,
            'omada_voucher_id' => $voucherData['omada_voucher_id'] ?? null,
            'voucher_code' => $voucherData['voucher_code'],
            'voucher_type' => $voucherType,
            'duration_minutes' => $voucherData['duration_minutes'],
            'status' => $voucherData['status'] ?? 'active',
            'issued_at' => $voucherData['issued_at'] ?? now(),
            'expires_at' => $voucherData['expires_at'] ?? now()->addMinutes($durationMinutes),
        ]);

        $logData = [
            'voucher_id' => $voucher->id,
            'action' => 'voucher_generated',
            'ip_address' => request()->ip(),
            'description' => ucfirst($voucherType) . ' WiFi voucher generated by assignment service.',
        ];

        if ($voucherType === 'student') {
            $logData['student_id'] = $subject->id;
        } else {
            $logData['visitor_id'] = $subject->id;
        }

        WifiAccessLog::create($logData);

        return [
            'id' => $voucher->id,
            'voucher_code' => $voucher->voucher_code,
            'status' => $voucher->status,
            'expires_at' => $voucher->expires_at,
            'student_id' => $voucherType === 'student' ? $subject->id : null,
            'visitor_id' => $voucherType === 'visitor' ? $subject->id : null,
        ];
    }
}
